version: "3.8"
services:
  db:
    image: postgres:13
    restart: always
    expose:
      - 5432
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_USER=academy
      - POSTGRES_PASSWORD=academy
      - POSTGRES_DB=academy
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  app:
    image: academy
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - db

volumes:
  postgres_data:
