version: "3.8"
services:
  app:
    image: academy
    build:
      context: ./
      dockerfile: Dockerfile.prod
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - db
    ports:
      - "3000:3000"

  db:
    image: postgres:13
    restart: always
    expose:
      - 5432
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=prisma
      - POSTGRES_PASSWORD=prisma
      - POSTGRES_DB=tests
